# Basic
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "min"
out_channel = "dias_bp_wave"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "mean"
out_channel = "mean_bp_wave"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "max"
out_channel = "sys_bp_wave"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "amplitude"
out_channel = "amp_bp_wave"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "period"
out_channel = "bp_period_wave"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "frequency"
out_channel = "bp_freq_wave"
out = "{name}"

# pi, ri, sd
[[command]]
class_name = "Arithmetic"
in =  "{name}"
in_channel = "amp_bp_wave"
in_channel_2 =  "mean_bp_wave"
format = "/"
out_channel = "pi_bp_wave"
out = "{name}"
[[command]]
class_name = "Arithmetic"
in =  "{name}"
in_channel = "amp_bp_wave"
in_channel_2 =  "sys_bp_wave"
format = "/"
out_channel = "ri_bp_wave"
out = "{name}"
[[command]]
class_name = "Arithmetic"
in =  "{name}"
in_channel = "sys_bp_wave"
in_channel_2 =  "dias_bp_wave"
format = "/"
out_channel = "sd_bp_wave"
out = "{name}"
[[command]]
class_name = "Arithmetic"
in =  "{name}"
in_channel = "bp_freq_wave"
num = 60
format = "*"
out_channel = "bp_freq_wave"
out = "{name}"


# Aggregations
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "dias_bp_wave"
format = "mean"
out_channel = "dias_bp"
mask = "{mask_name}"
weights = "bp_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "mean_bp_wave"
format = "mean"
out_channel = "mean_bp"
mask = "{mask_name}"
weights = "bp_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "sys_bp_wave"
format = "mean"
out_channel = "sys_bp"
mask = "{mask_name}"
weights = "bp_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "pi_bp_wave"
format = "mean"
out_channel = "pi_bp"
mask = "{mask_name}"
weights = "bp_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "ri_bp_wave"
format = "mean"
out_channel = "ri_bp"
mask = "{mask_name}"
weights = "bp_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "sd_bp_wave"
format = "mean"
out_channel = "sd_bp"
mask = "{mask_name}"
weights = "bp_period_wave"
out = "{name}"


[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "amp_bp_wave"
format = "mean"
out_channel = "amp_bp"
mask = "{mask_name}"
weights = "bp_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "amp_bp_wave"
format = "difference"
out_channel = "amp_bp_difference"
mask = "{mask_name}"
weights = "bp_period_wave"
out = "{name}"


[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "bp_freq_wave"
format = "mean"
out_channel = "HR_BP"
mask = "{mask_name}"
weights = "bp_period_wave"
out = "{name}"