# Inregards to respirac data there is no error handeling. We assume that anything that comes out of the system is truthful. They should all be partitioned by the same index, so I just use desired pco2 for the sake of.
# Idk why but sometimes we just have 1 or 2 extra markers in one channel. This prevents that issue from occuring. 
# They are also all weighted by the respirac_period variable.
 
# SAVE Header "desired_po2,desired_pco2,achievable_po2,achievable_pco2,po2,pco2,tidal_volume,respiration_rate,resting_po2,resting_pco2,breath_idx,o2_adjustment,co2_adjustment,g1_target_vol,g1_fco2,g1_fo2,G2_FCO2,g2_fo2"
# SAVE DATA "{desired_po2},{desired_pco2},{achievable_po2},{achievable_pco2},{po2_respirac},{pco2_respirac},{tidal_volume},{respiration_rate},{resting_po2},{resting_pco2},{breath_idx},{o2_adjustment},{co2_adjustment},{g1_target_vol},{g1_fco2},{g1_fo2},{G2_FCO2},{g2_fo2}"
 
# Partition
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "desired_pco2"
out_channel = "desired_pco2"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "desired_po2"
out_channel = "desired_po2"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "achievable_po2"
out_channel = "achievable_po2"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "achievable_pco2"
out_channel = "achievable_pco2"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "po2_respirac"
out_channel = "po2_respirac"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "pco2_respirac"
out_channel = "pco2_respirac"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "tidal_volume"
out_channel = "tidal_volume"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "respiration_rate"
out_channel = "respiration_rate"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "resting_po2"
out_channel = "resting_po2"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "resting_pco2"
out_channel = "resting_pco2"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "breath_idx"
out_channel = "breath_idx"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "o2_adjustment"
out_channel = "o2_adjustment"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "co2_adjustment"
out_channel = "co2_adjustment"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "g1_target_vol"
out_channel = "g1_target_vol"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "g1_fco2"
out_channel = "g1_fco2"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "g1_fo2"
out_channel = "g1_fo2"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "G2_FCO2"
out_channel = "G2_FCO2"
out = "{name}"
[[command]]
class_name = "partition"
in = "{name}"
index = "desired_pco2"
in_channel = "g2_fo2"
out_channel = "g2_fo2"
out = "{name}"

 
# Measurement
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "desired_pco2"
format = "period"
out_channel = "respiract_period_internal"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "desired_pco2"
format = "median"
out_channel = "desired_pco2"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "desired_po2"
format = "median"
out_channel = "desired_po2"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "achievable_po2"
format = "median"
out_channel = "achievable_po2"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "achievable_pco2"
format = "median"
out_channel = "achievable_pco2"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "po2_respirac"
format = "median"
out_channel = "po2_respirac"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "pco2_respirac"
format = "median"
out_channel = "pco2_respirac"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "tidal_volume"
format = "median"
out_channel = "tidal_volume"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "respiration_rate"
format = "median"
out_channel = "respiration_rate"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "resting_po2"
format = "median"
out_channel = "resting_po2"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "resting_pco2"
format = "median"
out_channel = "resting_pco2"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "breath_idx"
format = "median"
out_channel = "breath_idx"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "o2_adjustment"
format = "median"
out_channel = "o2_adjustment"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "co2_adjustment"
format = "median"
out_channel = "co2_adjustment"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "g1_target_vol"
format = "median"
out_channel = "g1_target_vol"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "g1_fco2"
format = "median"
out_channel = "g1_fco2"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "g1_fo2"
format = "median"
out_channel = "g1_fo2"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "G2_FCO2"
format = "median"
out_channel = "G2_FCO2"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "g2_fo2"
format = "median"
out_channel = "g2_fo2"
out = "{name}"
 
 
# Aggregation
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "desired_pco2"
format = "mean"
out_channel = "desired_pco2"
weights = "respiract_period_internal"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "desired_po2"
format = "mean"
out_channel = "desired_po2"
weights = "respiract_period_internal"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "achievable_po2"
format = "mean"
out_channel = "achievable_po2"
weights = "respiract_period_internal"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "achievable_pco2"
format = "mean"
out_channel = "achievable_pco2"
weights = "respiract_period_internal"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "po2_respirac"
format = "mean"
out_channel = "po2_respirac"
weights = "respiract_period_internal"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "pco2_respirac"
format = "mean"
out_channel = "pco2_respirac"
weights = "respiract_period_internal"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "tidal_volume"
format = "mean"
out_channel = "tidal_volume"
weights = "respiract_period_internal"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "respiration_rate"
format = "mean"
out_channel = "respiration_rate"
weights = "respiract_period_internal"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "resting_po2"
out_channel = "resting_po2"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "resting_pco2"
out_channel = "resting_pco2"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "breath_idx"
out_channel = "breath_idx"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "o2_adjustment"
out_channel = "o2_adjustment"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "co2_adjustment"
out_channel = "co2_adjustment"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "g1_target_vol"
out_channel = "g1_target_vol"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "g1_fco2"
out_channel = "g1_fco2"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "g1_fo2"
out_channel = "g1_fo2"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "G2_FCO2"
out_channel = "G2_FCO2"
[[command]]
class_name = "aggregate"
in = "{name}"
out = "{name}"
weights = "respiract_period_internal"
format = "mean"
in_channel = "g2_fo2"
out_channel = "g2_fo2"
 