# Basic
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "min"
out_channel = "dias_tono_wave"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "mean"
out_channel = "mean_tono_wave"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "max"
out_channel = "sys_tono_wave"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "amplitude"
out_channel = "amp_tono_wave"
out = "{name}"
[[command]]
class_name = "measurement"
in = "{name}"
in_channel = "{channel_name}"
format = "period"
out_channel = "tono_period_wave"
out = "{name}"

# pi, ri, sd
[[command]]
class_name = "Arithmetic"
in =  "{name}"
in_channel = "amp_tono_wave"
in_channel_2 =  "mean_tono_wave"
format = "/"
out_channel = "pi_tono_wave"
out = "{name}"
[[command]]
class_name = "Arithmetic"
in =  "{name}"
in_channel = "amp_tono_wave"
in_channel_2 =  "sys_tono_wave"
format = "/"
out_channel = "ri_tono_wave"
out = "{name}"
[[command]]
class_name = "Arithmetic"
in =  "{name}"
in_channel = "sys_tono_wave"
in_channel_2 =  "dias_tono_wave"
format = "/"
out_channel = "sd_tono_wave"
out = "{name}"

# Aggregations
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "dias_tono_wave"
format = "mean"
out_channel = "dias_tono"
mask = "{mask_name}"
weights = "tono_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "mean_tono_wave"
format = "mean"
out_channel = "mean_tono"
mask = "{mask_name}"
weights = "tono_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "sys_tono_wave"
format = "mean"
out_channel = "sys_tono"
mask = "{mask_name}"
weights = "tono_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "pi_tono_wave"
format = "mean"
out_channel = "pi_tono"
mask = "{mask_name}"
weights = "tono_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "ri_tono_wave"
format = "mean"
out_channel = "ri_tono"
mask = "{mask_name}"
weights = "tono_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "sd_tono_wave"
format = "mean"
out_channel = "sd_tono"
mask = "{mask_name}"
weights = "tono_period_wave"
out = "{name}"


[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "amp_tono_wave"
format = "mean"
out_channel = "amp_tono"
mask = "{mask_name}"
weights = "tono_period_wave"
out = "{name}"
[[command]]
class_name = "aggregate"
in = "{name}"
in_channel = "amp_tono_wave"
format = "difference"
out_channel = "amp_tono_difference"
mask = "{mask_name}"
weights = "tono_period_wave"
out = "{name}"